# Generated by Django 5.1.2 on 2024-11-19 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='singup',
            new_name='signup',
        ),
    ]
