# Generated by Django 5.1.2 on 2024-11-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel1', '0002_rename_singup_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
