# Generated by Django 5.1.2 on 2024-11-22 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel1', '0009_alter_profile_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile',
            field=models.ImageField(default='default.jpg', upload_to='media'),
        ),
    ]
