# Generated by Django 5.1.2 on 2024-11-22 07:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel1', '0010_alter_profile_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blog',
            new_name='blogmodel',
        ),
    ]
