# Generated by Django 5.1.2 on 2024-11-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel1', '0011_rename_blog_blogmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='photos',
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='travel_photos',
            field=models.ImageField(blank=True, null=True, upload_to='travel_photos'),
        ),
    ]
