# Generated by Django 5.1.2 on 2024-11-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel1', '0012_remove_blogmodel_photos_blogmodel_travel_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='travel_photos',
            field=models.ImageField(default='', upload_to='travel_photos'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile',
            field=models.ImageField(default='', upload_to='media'),
        ),
    ]
