# Generated by Django 5.1.2 on 2024-11-24 07:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel1', '0013_alter_blogmodel_travel_photos_alter_profile_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profile',
            new_name='profilemodel',
        ),
    ]
