# Generated by Django 5.1.2 on 2024-11-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel1', '0014_rename_profile_profilemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='profile',
            field=models.ImageField(default='', upload_to='profiles'),
        ),
    ]
