# Generated by Django 5.1.2 on 2024-11-26 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel1', '0017_profile_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='travel_photos',
            field=models.ImageField(blank=True, null=True, upload_to='travel_photos/'),
        ),
    ]
